# http://docs.ansible.com/ansible/galaxy.html#installing-multiple-roles-from-a-file
- name: geerlingguy.docker
  version: 2.0.5

- name: geerlingguy.ruby
  version: 2.4.2

- name: roquie.ansible-kontena-server
  version: 0.1.0

#
#- name: roquie.ansible-kontena-node
#  version: 0.1.0
