---

ansible_python_interpreter: "/usr/bin/python3"
ansible_ssh_port: 22
ansible_ssh_user: "vagrant"
ansible_ssh_private_key_file: "~/.vagrant.d/insecure_private_key"

docker_package: "docker-ce=17.03*"
