---
galaxy_info:
  author: roquie
  description: Installing Kontena CLI.
  license: MIT
  min_ansible_version: 2.2
  platforms:
    - name: Ubuntu
      versions:
        - xenial
  galaxy_tags:
    - kontena
    - kontena-cli

dependencies: []
