---

- hosts: [master, nodes]
  roles:
    - tersmitten.locales
    - geerlingguy.ntp
    #- mikegleasonjr.firewall
    - geerlingguy.docker
  tags:
    - base_configure

- hosts: master
  roles:
    - roquie.ansible-kontena-server
  post_tasks:
    - include_role: name=galexrt.ansible-ntpdate
  tags:
    - kontena_server

- hosts: nodes
  roles:
    - roquie.ansible-kontena-agent
  post_tasks:
    - include_role: name=galexrt.ansible-ntpdate
  tags:
    - kontena_agent

- hosts: cli
  roles:
    - geerlingguy.ruby
    - kontena-cli
  tags:
    - kontena_cli

