---

- hosts: [master, nodes]
  roles:
    - geerlingguy.docker
  tags:
    - docker

- hosts: master
  roles:
    - roquie.ansible-kontena-server
  tags:
    - kontena_server

- hosts: nodes
  roles:
    - kontena-node
  tags:
    - kontena_agent

- hosts: cli
  roles:
    - geerlingguy.ruby
    - kontena-cli
  tags:
    - kontena_cli

